set_property IOSTANDARD DIFF_SSTL18_I [get_ports {adc_clk_p[0]}]
set_property PACKAGE_PIN A17 [get_ports SPI_MISO]
set_property PACKAGE_PIN A16 [get_ports SPI_MOSI]
set_property PACKAGE_PIN K19 [get_ports SPI_SS]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_SCLK]
set_property PACKAGE_PIN L17 [get_ports SPI_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_SS]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_MOSI]


set_property PACKAGE_PIN D18 [get_ports {adc_clk_p[0]}]


set_property OFFCHIP_TERM NONE [get_ports {SPI_MOSI}]
set_property OFFCHIP_TERM NONE [get_ports {SPI_SCLK}]
set_property OFFCHIP_TERM NONE [get_ports {SPI_SS}]
set_property PACKAGE_PIN Y11 [get_ports SPI_MISO_JA1]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_MOSI_JA2]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_MISO_JA1]
set_property PACKAGE_PIN AA11 [get_ports SPI_MOSI_JA2]
set_property PACKAGE_PIN Y10 [get_ports SPI_SCLK_JA3]
set_property PACKAGE_PIN AA9 [get_ports SPI_SS_JA4]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_SCLK_JA3]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_SS_JA4]
